config/routes.rb
Naskit::Application.routes.draw do
  
  resources :movies

  resources :shows do
    resources :seasons do
      resources :episodes
    end
  end

  match "/search/:show/:season/:episode" => "search#url"
  match "/search" => "search#query"

  root :to => 'shows#index'
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :starrings, dependent: :destroy
  
  attr_accessible :name
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessible :description, :title, :number, :date, :season

  belongs_to :season

  has_many :starrings, as: :starrable, dependent: :destroy
  has_many :actors, through: :starrings

  has_one :show, :through => :season

  def as_json(*params)
    {
      :title => title,
      :number => number,
      :description => description,
      :season => season.number,
      :show => show.title
    }
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :description, :title

  has_many :starrings, as: :starrable, dependent: :destroy
  has_many :actors, through: :starrings
end

app/models/provider_update.rb
class ProviderUpdate < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :number, :episodes

  belongs_to :show
  
  has_many :episodes, dependent: :destroy
end

app/models/show.rb
class Show < ActiveRecord::Base
  attr_accessible :description, :title, :seasons, :poster

  has_many :seasons, dependent: :destroy
  has_many :episodes, through: :seasons, dependent: :destroy
  
  has_many :starrings, as: :starrable, dependent: :destroy
  has_many :actors, through: :starrings

  has_attached_file :poster

  def serializable_hash(options=nil)
    {
      title: title,
      seasons_count: seasons.count,
      episodes_count: episodes.count
    }
  end
end

app/models/starring.rb
class Starring < ActiveRecord::Base
  belongs_to :actor
  belongs_to :starrable, polymorphic: true
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :html, :xml, :json, :xbmc

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  
  protected

  def record_not_found
    redirect_to :root, :flash => { :error => t('errors.messages.not_found') }
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  inherit_resources
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def url
    search(params[:show], params[:season], params[:episode])
  end

  def query
    if params[:q].present?
      
      # is this a tv show in torrent format?
      if torrent = params[:q].match(/(?<show>.+)\.[sS]?(?<season>\d+)[eExX](?<episode>\d+)/)
        show      = torrent["show"].split(".").join(" ")
        season    = torrent["season"].to_i
        episode   = torrent["episode"].to_i

        search_episode(show, season, episode)
      else
        search_movie_or_episode(params[:q])
      end

    end
  end

  protected

  def search_movie_or_episode name
    if resource = Movie.where(title: name).first
      redirect_to movie_path(resource, format: params[:format]), status: 301
    elsif resource = Episode.where(title: name).first
      redirect_to show_season_episode_path(resource.show, resource.season, resource, format: params[:format]), status: 301
    else
      render :text => nil, :status => 404
    end
  end

  def search_episode show, season, episode
    show      = Show.where("lower(title) LIKE ?", show.downcase).first_or_initialize
    season    = show.seasons.where(number: season).first_or_initialize
    
    if episode = season.episodes.where(number: episode).first
      redirect_to show_season_episode_path(show, season, episode, format: params[:format]), status: 301
    else
      render :text => nil, :status => 404
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  inherit_resources
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  inherit_resources
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/application/index.html.haml
%h1= resource_class.model_name.human.pluralize

%ul
  - collection.each do |resource|
    %li= link_to resource.decorate.display_name, resource

app/views/application/show.html.haml
%h1= resource.decorate.display_name

= render 'details'

app/views/episodes/_details.html.haml
FUUU!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Naskit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/query.html.haml
= form_tag search_path, method: :get do
  = text_field_tag :q
  = submit_tag

app/views/seasons/_details.html.haml
%ul
  - resource.episodes.each do |episode|
    = link_to episode.decorate.display_name, show_season_episode_path(parent, resource, episode)

app/views/shows/_details.html.haml
%ul
  - resource.seasons.each do |season|
    %li
      = link_to season.decorate.display_name, show_season_path(resource, season)

      %ul
        - season.episodes.each do |episode|
          %li= link_to episode.decorate.display_name, show_season_episode_path(resource, season, episode)